job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-new-zealand
    WP_DB_NAME_PREFIX: planet4-nz_wordpress
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: www-dev.greenpeace.org
    APP_HOSTPATH: aotearoa
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GCLOUD_CLUSTER: p4-development
    GOOGLE_PROJECT_ID: planet-4-151612
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-new-zealand
    WP_DB_NAME: planet4-nz_wordpress_develop
    WP_STATELESS_BUCKET: planet4-aotearoa-stateless-develop
  release_build_env: &release_build_env
    GOOGLE_PROJECT_ID: planet4-production
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: www-stage.greenpeace.org
    APP_HOSTPATH: aotearoa
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: new-zealand
    HELM_RELEASE: planet4-new-zealand-release
    WP_DB_NAME: planet4-nz_wordpress_release
    WP_STATELESS_BUCKET: planet4-aotearoa-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: www.greenpeace.org
    APP_HOSTPATH: aotearoa
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: new-zealand
    HELM_RELEASE: planet4-new-zealand-master
    MIN_REPLICA_COUNT: 2
    WP_DB_NAME: planet4-nz_wordpress_master
    WP_STATELESS_BUCKET: planet4-aotearoa-stateless
