job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-new-zealand
    APP_HOSTPATH: new-zealand
    WP_DB_NAME_PREFIX: planet4-nz_wordpress
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GCLOUD_CLUSTER: p4-development
    GOOGLE_PROJECT_ID: planet-4-151612
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-new-zealand
    NEWRELIC_APPNAME: P4 New Zealand Development
    WP_DB_NAME: planet4-nz_wordpress_develop
    WP_STATELESS_BUCKET: planet4-new-zealand-stateless-develop
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: release.k8s.p4.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: new-zealand
    HELM_RELEASE: planet4-new-zealand-release
    NEWRELIC_APPNAME: P4 New Zealand Release
    WP_DB_NAME: planet4-nz_wordpress_release
    WP_STATELESS_BUCKET: planet4-new-zealand-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: www.greenpeace.org
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: new-zealand
    HELM_RELEASE: planet4-new-zealand-master
    MIN_REPLICA_COUNT: 2
    NEWRELIC_APPNAME: P4 New Zealand Production
    WP_DB_NAME: planet4-nz_wordpress_master
    WP_STATELESS_BUCKET: planet4-new-zealand-stateless